---
- hosts: all
  become: yes
  tasks:
       
       - name: install java openjdk8 on ubuntu 20.04
         apt:
            name: openjdk-8-jre
            state: present

       - name: install java openjdk8 on RedHat Machine
         yum:
            name: java-1.8.0-openjdk
            state: present 